### ISSUE TITLE
Icon for integration is missing

### ISSUE THREAD

**Issue by 35gh** [ateodorescu/home-assistant-ipmi#3]
In the integration page:
<img width="558" alt="Capture d’écran 2023-06-21 à 13 04 16" src="https://github.com/ateodorescu/home-assistant-ipmi/assets/90415090/70e96064-c4de-469d-8cc7-aed2ca955001">

**Comment by ateodorescu** [comment]
I don't know how this can be fixed. The html points to "https://brands.home-assistant.io/ipmi/logo.png" or "https://brands.home-assistant.io/ipmi/icon.png". It assumes that the integration is part of the core.

**Comment by 35gh** [comment]
The 2 links above return a 404 error for me.
It seems the "ipmi" domain is missing from HA brands GitHub repository: https://github.com/home-assistant/brands/tree/master/custom_integrations

**Comment by ateodorescu** [comment]
Done! The domain icon has been merged into the brands https://github.com/home-assistant/brands/pull/4512

**Comment by 35gh** [comment]
Thanks. I'm still not getting the icon in HA though, should the integration be named IPMI to match the domain?
